FROM reg.ops.com/library/jre8-alpine:latest
MAINTAINER zj-huawei

WORKDIR /ddhome/project/{{ PROJECT }}/{{ VERSION }}/server/{{ APP }}/

COPY {{ APP }}-zjhw.jar ./{{ APP }}.jar
COPY docker-entrypoint.sh ./docker-entrypoint.sh
{% if APP in ['huayun-lab-auth', 'huayun-lab-report', 'huayun-lab-data', 'ai-lab-auth', 'ai-lab-report', 'ai-lab-data', 'service-linux-user', 'service-lab-env'] %}
COPY bin ./bin 
RUN chmod -R +x bin
{% endif %}

{% if APP in ["iot-service-lab", "service-iot-lab"] %}
COPY cert /ddhome/local/cert/
{% endif %}

{% if PROJECT == 'iot' %}
RUN mkdir /ddhome/tmp
{% endif %}


{# 安装字体库 #}
{% if APP in ['ai-lab-resource', 'huayun-lab-resource', 'iot-service-device', 'iot-service-course', 'service-iot-device', 'service-iot-course', 'service-course'] %}
COPY fonts /usr/share/fonts/
RUN apk add --no-cache fontconfig &&\
    sed -i '27i <dir>/usr/share/fonts</dir>' /etc/fonts/fonts.conf &&\
    fc-cache  
{% endif %}               

{# 安装python3 #}
{% if APP in ["huayun-lab-auth", "huayun-lab-report", "ai-lab-auth", "ai-lab-report"] %}
RUN apk add --no-cache python3 py3-paramiko 
{% endif %}

{# 安装 ssh 和 expect #}
{% if APP in ["ai-lab-auth", "huayun-lab-auth", "ai-lab-report", "huayun-lab-report"] %}
RUN apk add --no-cache openssh-client expect 
{% endif %}

ENTRYPOINT ["sh", "./docker-entrypoint.sh"]
CMD []
